# Generated by Django 4.0.3 on 2022-04-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_prize_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dsec',
            new_name='desc',
        ),
    ]
