# Generated by Django 4.0.3 on 2022-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_dsec_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emaol', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
